export const EmployeData=[
    {
        id:1,
        Name:'Mark',
        email:'David@gmail.com',
        age:20
    },
    {
        id:2,
        Name:'Dark',
        email:'Mavid@gmail.com',
        age:22
    },
    {
        id:3,
        Name:'Sark',
        email:'Savid@gmail.com',
        age:25
    },
    {
        id:4,
        Name:'John',
        email:'John@gmail.com',
        age:25
    },
]